### ISSUE TITLE
Bulk user flash upload

### ISSUE THREAD

**Issue by gadyke** [c0pperdragon/OS816#2]
Hi there,

Hope you don't mind, I've set this issue up separately from #1 (which I'll close in the near future!) as it's on a separate topic.

At the moment I think I can see the serial upload/flash routine for the monitor tops out at ~255 bytes of user code (though tell me if I'm wrong about that). I really like the utility of using a bootloader/monitor that sits above user code so I was wondering whether that's easily extendable to bigger chunks of user code?

Clearly if need be we could just compose a flash image with the user code and the bootloader and manually flash it in a programmer - but that's nowhere near as elegant as your "ISP" solution!

Regards,

Greg

**Comment by c0pperdragon** [comment]
The resident boot loader code is located at FFF000 - FFFFFF  (total 4Kbytes). It contains some low-level functions for accessing IO and flash programming. The boot monitor command line interface is also inside these 4K. 
The main reason for this specific size is the fact that the flash IC has this page size, so only one flash page is reserved for the boot loader and everything else can be freely re-programmed without danger of damaging the boot loader itself. There are even some guards in place to protect against that.

Of course there is no need to keep to this 4K size. You can go ahead and come up with whatevery fits your needs. But you are already quite on your own here with your customized memory map that needs modification of my OS816 bios code.

**Comment by gadyke** [comment]
Sorry I should have been clearer - I was talking about the function in monitor.c to read in hex files and write to flash.

I was saying that it looked like the code was hard limited to only short snippets of hex (100 bytes) and I was asking how you would go about 'uploading' bigger chunks, but I've since realised that that's the limit per-record (per-line) of hex - so there shouldn't be any hard limit!

Also - I totally accept your point about the changes I'm making to the memory map for my fork will mean there will be changes needed to the OS816 code that I'm on my own to debug - I promise I'll only raise an issue if it looks like it's memory map-independent!

Regards,

Greg

**Comment by c0pperdragon** [comment]
I guess it should be possible for you to modify the bios in a way to keep compatibility with the user code. 
Everything that directly touches the hardware is located in boot.asm .
