### ISSUE TITLE
Incorrect A14, A15 and A17?

### ISSUE THREAD

**Issue by HeathenUK** [c0pperdragon/OS816#4]
I was just glancing at your original schematic and PCB routing when sense checking my own design and realised that you seem to have A15 wired to A17, A17 to A14 and A15 to A14. As far as I understand the design this shouldn't be intentional but equally may not have shown up given how high up the RAM addresses it occurs?

**Comment by c0pperdragon** [comment]
I changed the wiring to get a simpler board layout. When you think about it, it makes absolutely no difference how you wire up the address pins on a static ram.Same holds true for the data pins.

**Comment by HeathenUK** [comment]
I did wonder about that, I guess you're right as long as it's consistent throughout runtime - it feels like sacrilege though!
